// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List/search images by owner/filters
	// (GET /v1/images)
	ListImages(c *gin.Context, params ListImagesParams)
	// Confirm upload (HEAD against S3), persist metadata
	// (POST /v1/images/confirm)
	ConfirmUpload(c *gin.Context)
	// Create a presigned PUT URL for uploading an image to MinIO/S3
	// (POST /v1/images/presign)
	CreatePresign(c *gin.Context)
	// Promote images from a product draft to a final product
	// (POST /v1/images/promote)
	PromoteImages(c *gin.Context)
	// Delete image (soft or hard, per policy)
	// (DELETE /v1/images/{id})
	DeleteImage(c *gin.Context, id string, params DeleteImageParams)
	// Get image metadata
	// (GET /v1/images/{id})
	GetImage(c *gin.Context, id string)
	// Update image metadata (alt, role, order)
	// (PATCH /v1/images/{id})
	UpdateImage(c *gin.Context, id string)
	// Generate a signed imgproxy URL for delivery with requested params
	// (GET /v1/images/{id}/url)
	GetDeliveryUrl(c *gin.Context, id string, params GetDeliveryUrlParams)
	// Trigger (or retry) variant generation for an image
	// (POST /v1/internal/images/process)
	ProcessImage(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ListImages operation middleware
func (siw *ServerInterfaceWrapper) ListImages(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListImagesParams

	// ------------- Optional query parameter "ownerType" -------------

	err = runtime.BindQueryParameter("form", true, false, "ownerType", c.Request.URL.Query(), &params.OwnerType)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter ownerType: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "ownerId" -------------

	err = runtime.BindQueryParameter("form", true, false, "ownerId", c.Request.URL.Query(), &params.OwnerId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter ownerId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", c.Request.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter status: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListImages(c, params)
}

// ConfirmUpload operation middleware
func (siw *ServerInterfaceWrapper) ConfirmUpload(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ConfirmUpload(c)
}

// CreatePresign operation middleware
func (siw *ServerInterfaceWrapper) CreatePresign(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreatePresign(c)
}

// PromoteImages operation middleware
func (siw *ServerInterfaceWrapper) PromoteImages(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PromoteImages(c)
}

// DeleteImage operation middleware
func (siw *ServerInterfaceWrapper) DeleteImage(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteImageParams

	// ------------- Optional query parameter "hard" -------------

	err = runtime.BindQueryParameter("form", true, false, "hard", c.Request.URL.Query(), &params.Hard)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter hard: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteImage(c, id, params)
}

// GetImage operation middleware
func (siw *ServerInterfaceWrapper) GetImage(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetImage(c, id)
}

// UpdateImage operation middleware
func (siw *ServerInterfaceWrapper) UpdateImage(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateImage(c, id)
}

// GetDeliveryUrl operation middleware
func (siw *ServerInterfaceWrapper) GetDeliveryUrl(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDeliveryUrlParams

	// ------------- Optional query parameter "variant" -------------

	err = runtime.BindQueryParameter("form", true, false, "variant", c.Request.URL.Query(), &params.Variant)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter variant: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "w" -------------

	err = runtime.BindQueryParameter("form", true, false, "w", c.Request.URL.Query(), &params.W)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter w: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "h" -------------

	err = runtime.BindQueryParameter("form", true, false, "h", c.Request.URL.Query(), &params.H)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter h: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "fit" -------------

	err = runtime.BindQueryParameter("form", true, false, "fit", c.Request.URL.Query(), &params.Fit)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter fit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "format" -------------

	err = runtime.BindQueryParameter("form", true, false, "format", c.Request.URL.Query(), &params.Format)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter format: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "quality" -------------

	err = runtime.BindQueryParameter("form", true, false, "quality", c.Request.URL.Query(), &params.Quality)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter quality: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "dpr" -------------

	err = runtime.BindQueryParameter("form", true, false, "dpr", c.Request.URL.Query(), &params.Dpr)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter dpr: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "ttlSeconds" -------------

	err = runtime.BindQueryParameter("form", true, false, "ttlSeconds", c.Request.URL.Query(), &params.TtlSeconds)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter ttlSeconds: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetDeliveryUrl(c, id, params)
}

// ProcessImage operation middleware
func (siw *ServerInterfaceWrapper) ProcessImage(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ProcessImage(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/v1/images", wrapper.ListImages)
	router.POST(options.BaseURL+"/v1/images/confirm", wrapper.ConfirmUpload)
	router.POST(options.BaseURL+"/v1/images/presign", wrapper.CreatePresign)
	router.POST(options.BaseURL+"/v1/images/promote", wrapper.PromoteImages)
	router.DELETE(options.BaseURL+"/v1/images/:id", wrapper.DeleteImage)
	router.GET(options.BaseURL+"/v1/images/:id", wrapper.GetImage)
	router.PATCH(options.BaseURL+"/v1/images/:id", wrapper.UpdateImage)
	router.GET(options.BaseURL+"/v1/images/:id/url", wrapper.GetDeliveryUrl)
	router.POST(options.BaseURL+"/v1/internal/images/process", wrapper.ProcessImage)
}

type ListImagesRequestObject struct {
	Params ListImagesParams
}

type ListImagesResponseObject interface {
	VisitListImagesResponse(w http.ResponseWriter) error
}

type ListImages200JSONResponse struct {
	Items    *[]Image `json:"items,omitempty"`
	Page     *int     `json:"page,omitempty"`
	PageSize *int     `json:"pageSize,omitempty"`
	Total    *int     `json:"total,omitempty"`
}

func (response ListImages200JSONResponse) VisitListImagesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListImages500ApplicationProblemPlusJSONResponse Problem

func (response ListImages500ApplicationProblemPlusJSONResponse) VisitListImagesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ConfirmUploadRequestObject struct {
	Body *ConfirmUploadJSONRequestBody
}

type ConfirmUploadResponseObject interface {
	VisitConfirmUploadResponse(w http.ResponseWriter) error
}

type ConfirmUpload201JSONResponse Image

func (response ConfirmUpload201JSONResponse) VisitConfirmUploadResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type ConfirmUpload400ApplicationProblemPlusJSONResponse Problem

func (response ConfirmUpload400ApplicationProblemPlusJSONResponse) VisitConfirmUploadResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ConfirmUpload404ApplicationProblemPlusJSONResponse Problem

func (response ConfirmUpload404ApplicationProblemPlusJSONResponse) VisitConfirmUploadResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ConfirmUpload409ApplicationProblemPlusJSONResponse Problem

func (response ConfirmUpload409ApplicationProblemPlusJSONResponse) VisitConfirmUploadResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type ConfirmUpload500ApplicationProblemPlusJSONResponse Problem

func (response ConfirmUpload500ApplicationProblemPlusJSONResponse) VisitConfirmUploadResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreatePresignRequestObject struct {
	Body *CreatePresignJSONRequestBody
}

type CreatePresignResponseObject interface {
	VisitCreatePresignResponse(w http.ResponseWriter) error
}

type CreatePresign200JSONResponse PresignResponse

func (response CreatePresign200JSONResponse) VisitCreatePresignResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreatePresign400ApplicationProblemPlusJSONResponse Problem

func (response CreatePresign400ApplicationProblemPlusJSONResponse) VisitCreatePresignResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreatePresign500ApplicationProblemPlusJSONResponse Problem

func (response CreatePresign500ApplicationProblemPlusJSONResponse) VisitCreatePresignResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PromoteImagesRequestObject struct {
	Body *PromoteImagesJSONRequestBody
}

type PromoteImagesResponseObject interface {
	VisitPromoteImagesResponse(w http.ResponseWriter) error
}

type PromoteImages200JSONResponse struct {
	Promoted *[]Image `json:"promoted,omitempty"`
}

func (response PromoteImages200JSONResponse) VisitPromoteImagesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PromoteImages400ApplicationProblemPlusJSONResponse Problem

func (response PromoteImages400ApplicationProblemPlusJSONResponse) VisitPromoteImagesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PromoteImages404ApplicationProblemPlusJSONResponse Problem

func (response PromoteImages404ApplicationProblemPlusJSONResponse) VisitPromoteImagesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PromoteImages409ApplicationProblemPlusJSONResponse Problem

func (response PromoteImages409ApplicationProblemPlusJSONResponse) VisitPromoteImagesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type PromoteImages500ApplicationProblemPlusJSONResponse Problem

func (response PromoteImages500ApplicationProblemPlusJSONResponse) VisitPromoteImagesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteImageRequestObject struct {
	Id     string `json:"id"`
	Params DeleteImageParams
}

type DeleteImageResponseObject interface {
	VisitDeleteImageResponse(w http.ResponseWriter) error
}

type DeleteImage204Response struct {
}

func (response DeleteImage204Response) VisitDeleteImageResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteImage404ApplicationProblemPlusJSONResponse Problem

func (response DeleteImage404ApplicationProblemPlusJSONResponse) VisitDeleteImageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteImage500ApplicationProblemPlusJSONResponse Problem

func (response DeleteImage500ApplicationProblemPlusJSONResponse) VisitDeleteImageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetImageRequestObject struct {
	Id string `json:"id"`
}

type GetImageResponseObject interface {
	VisitGetImageResponse(w http.ResponseWriter) error
}

type GetImage200JSONResponse Image

func (response GetImage200JSONResponse) VisitGetImageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetImage404ApplicationProblemPlusJSONResponse Problem

func (response GetImage404ApplicationProblemPlusJSONResponse) VisitGetImageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetImage500ApplicationProblemPlusJSONResponse Problem

func (response GetImage500ApplicationProblemPlusJSONResponse) VisitGetImageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateImageRequestObject struct {
	Id   string `json:"id"`
	Body *UpdateImageJSONRequestBody
}

type UpdateImageResponseObject interface {
	VisitUpdateImageResponse(w http.ResponseWriter) error
}

type UpdateImage200JSONResponse Image

func (response UpdateImage200JSONResponse) VisitUpdateImageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateImage404ApplicationProblemPlusJSONResponse Problem

func (response UpdateImage404ApplicationProblemPlusJSONResponse) VisitUpdateImageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateImage500ApplicationProblemPlusJSONResponse Problem

func (response UpdateImage500ApplicationProblemPlusJSONResponse) VisitUpdateImageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetDeliveryUrlRequestObject struct {
	Id     string `json:"id"`
	Params GetDeliveryUrlParams
}

type GetDeliveryUrlResponseObject interface {
	VisitGetDeliveryUrlResponse(w http.ResponseWriter) error
}

type GetDeliveryUrl200JSONResponse struct {
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
	Url       string     `json:"url"`
}

func (response GetDeliveryUrl200JSONResponse) VisitGetDeliveryUrlResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetDeliveryUrl404ApplicationProblemPlusJSONResponse Problem

func (response GetDeliveryUrl404ApplicationProblemPlusJSONResponse) VisitGetDeliveryUrlResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetDeliveryUrl500ApplicationProblemPlusJSONResponse Problem

func (response GetDeliveryUrl500ApplicationProblemPlusJSONResponse) VisitGetDeliveryUrlResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ProcessImageRequestObject struct {
	Body *ProcessImageJSONRequestBody
}

type ProcessImageResponseObject interface {
	VisitProcessImageResponse(w http.ResponseWriter) error
}

type ProcessImage202Response struct {
}

func (response ProcessImage202Response) VisitProcessImageResponse(w http.ResponseWriter) error {
	w.WriteHeader(202)
	return nil
}

type ProcessImage500ApplicationProblemPlusJSONResponse Problem

func (response ProcessImage500ApplicationProblemPlusJSONResponse) VisitProcessImageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List/search images by owner/filters
	// (GET /v1/images)
	ListImages(ctx context.Context, request ListImagesRequestObject) (ListImagesResponseObject, error)
	// Confirm upload (HEAD against S3), persist metadata
	// (POST /v1/images/confirm)
	ConfirmUpload(ctx context.Context, request ConfirmUploadRequestObject) (ConfirmUploadResponseObject, error)
	// Create a presigned PUT URL for uploading an image to MinIO/S3
	// (POST /v1/images/presign)
	CreatePresign(ctx context.Context, request CreatePresignRequestObject) (CreatePresignResponseObject, error)
	// Promote images from a product draft to a final product
	// (POST /v1/images/promote)
	PromoteImages(ctx context.Context, request PromoteImagesRequestObject) (PromoteImagesResponseObject, error)
	// Delete image (soft or hard, per policy)
	// (DELETE /v1/images/{id})
	DeleteImage(ctx context.Context, request DeleteImageRequestObject) (DeleteImageResponseObject, error)
	// Get image metadata
	// (GET /v1/images/{id})
	GetImage(ctx context.Context, request GetImageRequestObject) (GetImageResponseObject, error)
	// Update image metadata (alt, role, order)
	// (PATCH /v1/images/{id})
	UpdateImage(ctx context.Context, request UpdateImageRequestObject) (UpdateImageResponseObject, error)
	// Generate a signed imgproxy URL for delivery with requested params
	// (GET /v1/images/{id}/url)
	GetDeliveryUrl(ctx context.Context, request GetDeliveryUrlRequestObject) (GetDeliveryUrlResponseObject, error)
	// Trigger (or retry) variant generation for an image
	// (POST /v1/internal/images/process)
	ProcessImage(ctx context.Context, request ProcessImageRequestObject) (ProcessImageResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// ListImages operation middleware
func (sh *strictHandler) ListImages(ctx *gin.Context, params ListImagesParams) {
	var request ListImagesRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListImages(ctx, request.(ListImagesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListImages")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(ListImagesResponseObject); ok {
		if err := validResponse.VisitListImagesResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// ConfirmUpload operation middleware
func (sh *strictHandler) ConfirmUpload(ctx *gin.Context) {
	var request ConfirmUploadRequestObject

	var body ConfirmUploadJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ConfirmUpload(ctx, request.(ConfirmUploadRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ConfirmUpload")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(ConfirmUploadResponseObject); ok {
		if err := validResponse.VisitConfirmUploadResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreatePresign operation middleware
func (sh *strictHandler) CreatePresign(ctx *gin.Context) {
	var request CreatePresignRequestObject

	var body CreatePresignJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreatePresign(ctx, request.(CreatePresignRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreatePresign")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(CreatePresignResponseObject); ok {
		if err := validResponse.VisitCreatePresignResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PromoteImages operation middleware
func (sh *strictHandler) PromoteImages(ctx *gin.Context) {
	var request PromoteImagesRequestObject

	var body PromoteImagesJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PromoteImages(ctx, request.(PromoteImagesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PromoteImages")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PromoteImagesResponseObject); ok {
		if err := validResponse.VisitPromoteImagesResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteImage operation middleware
func (sh *strictHandler) DeleteImage(ctx *gin.Context, id string, params DeleteImageParams) {
	var request DeleteImageRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteImage(ctx, request.(DeleteImageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteImage")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(DeleteImageResponseObject); ok {
		if err := validResponse.VisitDeleteImageResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetImage operation middleware
func (sh *strictHandler) GetImage(ctx *gin.Context, id string) {
	var request GetImageRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetImage(ctx, request.(GetImageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetImage")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetImageResponseObject); ok {
		if err := validResponse.VisitGetImageResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateImage operation middleware
func (sh *strictHandler) UpdateImage(ctx *gin.Context, id string) {
	var request UpdateImageRequestObject

	request.Id = id

	var body UpdateImageJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateImage(ctx, request.(UpdateImageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateImage")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(UpdateImageResponseObject); ok {
		if err := validResponse.VisitUpdateImageResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDeliveryUrl operation middleware
func (sh *strictHandler) GetDeliveryUrl(ctx *gin.Context, id string, params GetDeliveryUrlParams) {
	var request GetDeliveryUrlRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetDeliveryUrl(ctx, request.(GetDeliveryUrlRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDeliveryUrl")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetDeliveryUrlResponseObject); ok {
		if err := validResponse.VisitGetDeliveryUrlResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// ProcessImage operation middleware
func (sh *strictHandler) ProcessImage(ctx *gin.Context) {
	var request ProcessImageRequestObject

	var body ProcessImageJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ProcessImage(ctx, request.(ProcessImageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ProcessImage")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(ProcessImageResponseObject); ok {
		if err := validResponse.VisitProcessImageResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xa6W7cOBJ+FUK7P2xspw9fSQzMD19J5MnEHh8zyWSDDFssSYwlUiEp2x3DwD7EPuE+",
	"yYKH1FKLbXc7m4yBzR+jLYlksY6vviryJoh4XnAGTMlg+yaQUQo5Nj/3OIupyE/gcwlS6SeF4AUIRcG8",
	"x5l5qCYFBNuBVIKyJLjtBVEK0YUsc/2SgIwELRTlLNgOoJ/0e+j01c7a5hZK4RrFXCBMCNXvcYYoU5AI",
	"qibIzBH0AlZmGR5nEGwrUUKvu5jg+uVN8HcBcbAd/G0w3c7A7WUQ5jiBE/3hbS8oi4xjcsYvgHUFPKUJ",
	"A4IOfz9DSn+BYsFzVAiQNGFIgCw4kxD0gpyy18ASlQbbo45UWiz4XFIBJNh+31qxZ7TmxP5Qj+TjTxAp",
	"LZ6RdQldC8AKyI55G3ORYxVsBwQreKJoriXtDEmxTPXX96qWEv0ZXOO80F8FNE8+Dke/7Ozu7R+86Pf7",
	"vskvYOLR6jq6gAniMVIpIC5oQo21zVY9k+Ract9uc05oTJfbLr9iIELinc+8OzNP7/ago/rDh7icpF+a",
	"+zFeDsK8UViVcqHJTu2n2oNF1tXxUeFi6D//+jciVECk0PnJa0RjVJTjjEaIC3RJMSoEv54sElmXWFDs",
	"UIEqyO8V8zc7QI91k2Eh8KQTD5QETdVPTeRUa72oipTc2tXosFZY0/FbbjE3pI6xitLF44oLAqKr5WMu",
	"DVYhyowvF4KTMlIowVkGYjL1v4aNl3SX23k7OHHzANPQ+j7IMdV4Ml2aqxREQwPT3TQdqDFDAYzoLypQ",
	"BG2CQvAIpLTPBWCip44xzcxbAhkoIN5VjprRVK9hNbQvcKzs7PpfvaScI+yxRdu5aSfiTAFTswsZNBl8",
	"KkDLbf8p2PT3FYyL+h98SWO9dhPbGqM7IsU0A4YtKE3HyJRD/1OR3JcOWhjU9iejFhTu6+A0H6Fwf8Hp",
	"vh9szabIL6DdfzxRoAMxx9c01yYYDTeebT7dGhrx3aNuPMxggR8Gan33WtauUWBu9qx9xyXqjvPAdUEF",
	"yNCT+8/OXut9SYg4I9Ifyk7yV4AJCAsgNXs5bi3UMVpH1uWIiNYDpoyyBNmBKAeFCVYYrVzApIdqTbqf",
	"IekhraceAhX1V31ubSc6t+mkzqaloMFilEaP7M3Qm6mCu+ryW4yPM/BwxZMXe0+fDZ8i9wHaB4VpJi2G",
	"NBRNzHOvykEILtr5qz02ppD5mUEOUjoi1tVEZxPtdNcLKJMKswju12uTAnT9TVGV+ZmQEjiCOaxGOWRY",
	"yqLKBphdsZZqjsVyrmAuPhONaVa0e3DMgK7smj6MEc+pUkAMmynsgghnjjPKikoSl1Vq886LutoyOb8E",
	"74KaBJnVIl5MkOJVapeDG/crJLeDfr+PMCNIgJ4I8Ywgq5gGXow5zwAzvVo98l5lzFij0mFzCie8zyQV",
	"8+rYIgWapMrvXAtQdUcBl+Lo3Typ0jIfe11/Li++okSlvlfd6Ls18Rbz7l52jkNTYOaY4UQDp/O3Oq4s",
	"L0KnIC5pBGjnOAx6wSUIaceP+sP+2qZJuAUwXNBgO1jvD/vr2ixYpUbDg8vRYOrHCRhlaxNgLYW2fPCa",
	"ShVWSxdY4ByUyR7vbwKqF/pcWgJnVdfKiTYxL5Hnb3t3TGq8aDplxwf9Q2vOvZgwrWpl3pyFLf2mMxKI",
	"canJ+Og+/jB/wlNXI3Qn3Rw2iMra8D6O8kFHo6UQxqxrw2GDeZq0XxQZjYyNB58kZ9PWSTcIa3RaqIqy",
	"DQAPdBXtfNSIlnrv/iTCFc4Wj6WZsvJnPcXmnfsvbIb+R1cPd+2zSvyeRUOmQOhaVkcmCHSg87iRV5Z5",
	"jsXEBdVAAhZRWiWF8cQyn0FMMxNgesQ0PgeR7WcZA3HpCVTX8Do3hMbxF5Bql5PJAuZ3gGcMzC/030uc",
	"lVBXmcFuhqMLJBngCy1dxcirQq7FBwOYHKbjlxE9oofh+Zdw9IaGMmQnm9FeuBVeFG9/2zt83u/3rfoW",
	"0/hMP++2nXR0Arzt+P1oKb9fwK891jYgTHhU5sAUcoW9druN7+t2u5igWjl69Y3vufq5K8EdoUCMKxTz",
	"kjlNPP+esmhPyWik0Irt2JoAQldUpYYWSJyDoQk4Mw0C5CILyOojRQvn+lXptPLqYGcf4QRroo5O11d7",
	"qNBpX6q6qpoFD9cDvgM8jN+6AvSrwMOQv4OKPjVgpNX5aLcsph2KZlui7jsEJFYfh6PDnd29/dHawYv1",
	"lxubr7YOf376y5tnx7+22nHbsy2bNkpZzjZ6tr6xubUE9sw0dRbCnuHXgW6j1H+uM76neN+zkz/pavT2",
	"QXgMk8NR9PL68t3vv9IjJile+20z/MRpZLvljXo7SJUq5PZgoHkI7/f7b5/s5F+eHFiZf3o+HP6zHA7X",
	"tuzjU5owrEoBPy0J+bP9EE/4uE+AmHbxo0HfxwgiRjcIV+dBQNDx+ZlRmy4zrHV1nYGZQ0zF0S+UhUeD",
	"0/Uunpiidj6euDK7Lhwejic4y1qBEQue2+C+HxdsvexOCPix695qjCAfh6Of3777ww5d33DKGktbAj1o",
	"taqQeu87a3KP3r77Q///YUnZlgiZVnvjf4ZU86oD5wjkawuERdi83RvlDOl5bSf//41nWbr5hiv04q9m",
	"V6TUhbfrb+l3jxP3XERUZZY5Esf10ZdhKxrpMIrNsW51xDMDeDeU3NqaXPtdF+/2zfPQnQn72iQFVum0",
	"4KckmA3MB/Q2UiyIv2UQ40xC745God1I1f9DlFmsb/YH93eRgIgLoulljrVVsomnU+hpOGx4DougEbF/",
	"dcw8Qj+1+nGpd0XyWCEukLawofeo4BmNJqZE8fbpXoL6Zu73tR2lB1XWtnnzw1c8vvISlHOUacFnurr2",
	"kkDbMc4Lgr8hNH1Yltwt4Rb22sM3IDEPckiryB8INs8rrX5mHBOt4ExVZ7nmXsqqL7cO3LWgedC2Dxm9",
	"BDGxh7bfK79OT5CaKbaplzc4B8RjW1Y9SYBpuYFUZ09ohcYIrqlUctV3iOlf9qq14EPOE9KvniGm7W1X",
	"F1UifgnC3WywPZWYZtomlElKzEWIUplfHxberzvq9RKZoLpwF/RqGRqP3MUYcyWmF7h2UsGSJVb/XOKM",
	"qol/+WebrTsiw4cd75BCzD8uqmZfb8w97G/Ws7MyH981uVLZaX3rY56fhjGieWJuzyEqbcszKQUQ2xeV",
	"VYsGmb6TCb0ewgz96fpQfyITc+iKZhkaA6Isykp75Woq9Dc/i3LCLHOBsnzI/RCReQ6qfzCUpRiKRUKE",
	"kWs21e5XdZyIg3TrgY5DALGO1jj+cqs1Wk8RSHln60l/UBGeh5KTmVNQPducGyuFANc28ucGe9VSf4NW",
	"qrwgQa32EI1RKU0Q3XtNZxEOtOa5RRBFUGitao03Lkc+Tq85EzRJQKAVLpAAJSardSJ1qZVyZq/duyal",
	"Xun2vwEAAP//A5wYMAYwAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
