// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List/search images by owner/filters
	// (GET /images)
	ListImages(c *gin.Context, params ListImagesParams)
	// Confirm upload (HEAD against S3), persist metadata
	// (POST /images/confirm)
	ConfirmUpload(c *gin.Context)
	// Create a presigned PUT URL for uploading an image to MinIO/S3
	// (POST /images/presign)
	CreatePresign(c *gin.Context)
	// Promote images from a product draft to a final product
	// (POST /images/promote)
	PromoteImages(c *gin.Context)
	// Delete image (soft or hard, per policy)
	// (DELETE /images/{id})
	DeleteImage(c *gin.Context, id string, params DeleteImageParams)
	// Get image metadata
	// (GET /images/{id})
	GetImage(c *gin.Context, id string)
	// Update image metadata (alt, role, order)
	// (PATCH /images/{id})
	UpdateImage(c *gin.Context, id string)
	// Generate a signed imgproxy URL for delivery with requested params
	// (GET /images/{id}/url)
	GetDeliveryUrl(c *gin.Context, id string, params GetDeliveryUrlParams)
	// Trigger (or retry) variant generation for an image
	// (POST /internal/images/process)
	ProcessImage(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ListImages operation middleware
func (siw *ServerInterfaceWrapper) ListImages(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListImagesParams

	// ------------- Optional query parameter "ownerType" -------------

	err = runtime.BindQueryParameter("form", true, false, "ownerType", c.Request.URL.Query(), &params.OwnerType)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter ownerType: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "ownerId" -------------

	err = runtime.BindQueryParameter("form", true, false, "ownerId", c.Request.URL.Query(), &params.OwnerId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter ownerId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", c.Request.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter status: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameter("form", true, false, "pageSize", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter pageSize: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListImages(c, params)
}

// ConfirmUpload operation middleware
func (siw *ServerInterfaceWrapper) ConfirmUpload(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ConfirmUpload(c)
}

// CreatePresign operation middleware
func (siw *ServerInterfaceWrapper) CreatePresign(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreatePresign(c)
}

// PromoteImages operation middleware
func (siw *ServerInterfaceWrapper) PromoteImages(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PromoteImages(c)
}

// DeleteImage operation middleware
func (siw *ServerInterfaceWrapper) DeleteImage(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteImageParams

	// ------------- Optional query parameter "hard" -------------

	err = runtime.BindQueryParameter("form", true, false, "hard", c.Request.URL.Query(), &params.Hard)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter hard: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteImage(c, id, params)
}

// GetImage operation middleware
func (siw *ServerInterfaceWrapper) GetImage(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetImage(c, id)
}

// UpdateImage operation middleware
func (siw *ServerInterfaceWrapper) UpdateImage(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateImage(c, id)
}

// GetDeliveryUrl operation middleware
func (siw *ServerInterfaceWrapper) GetDeliveryUrl(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDeliveryUrlParams

	// ------------- Optional query parameter "variant" -------------

	err = runtime.BindQueryParameter("form", true, false, "variant", c.Request.URL.Query(), &params.Variant)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter variant: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "w" -------------

	err = runtime.BindQueryParameter("form", true, false, "w", c.Request.URL.Query(), &params.W)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter w: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "h" -------------

	err = runtime.BindQueryParameter("form", true, false, "h", c.Request.URL.Query(), &params.H)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter h: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "fit" -------------

	err = runtime.BindQueryParameter("form", true, false, "fit", c.Request.URL.Query(), &params.Fit)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter fit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "format" -------------

	err = runtime.BindQueryParameter("form", true, false, "format", c.Request.URL.Query(), &params.Format)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter format: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "quality" -------------

	err = runtime.BindQueryParameter("form", true, false, "quality", c.Request.URL.Query(), &params.Quality)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter quality: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "dpr" -------------

	err = runtime.BindQueryParameter("form", true, false, "dpr", c.Request.URL.Query(), &params.Dpr)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter dpr: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "ttlSeconds" -------------

	err = runtime.BindQueryParameter("form", true, false, "ttlSeconds", c.Request.URL.Query(), &params.TtlSeconds)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter ttlSeconds: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetDeliveryUrl(c, id, params)
}

// ProcessImage operation middleware
func (siw *ServerInterfaceWrapper) ProcessImage(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ProcessImage(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/images", wrapper.ListImages)
	router.POST(options.BaseURL+"/images/confirm", wrapper.ConfirmUpload)
	router.POST(options.BaseURL+"/images/presign", wrapper.CreatePresign)
	router.POST(options.BaseURL+"/images/promote", wrapper.PromoteImages)
	router.DELETE(options.BaseURL+"/images/:id", wrapper.DeleteImage)
	router.GET(options.BaseURL+"/images/:id", wrapper.GetImage)
	router.PATCH(options.BaseURL+"/images/:id", wrapper.UpdateImage)
	router.GET(options.BaseURL+"/images/:id/url", wrapper.GetDeliveryUrl)
	router.POST(options.BaseURL+"/internal/images/process", wrapper.ProcessImage)
}

type ListImagesRequestObject struct {
	Params ListImagesParams
}

type ListImagesResponseObject interface {
	VisitListImagesResponse(w http.ResponseWriter) error
}

type ListImages200JSONResponse struct {
	Items    *[]Image `json:"items,omitempty"`
	Page     *int     `json:"page,omitempty"`
	PageSize *int     `json:"pageSize,omitempty"`
	Total    *int     `json:"total,omitempty"`
}

func (response ListImages200JSONResponse) VisitListImagesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListImages500ApplicationProblemPlusJSONResponse Problem

func (response ListImages500ApplicationProblemPlusJSONResponse) VisitListImagesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ConfirmUploadRequestObject struct {
	Body *ConfirmUploadJSONRequestBody
}

type ConfirmUploadResponseObject interface {
	VisitConfirmUploadResponse(w http.ResponseWriter) error
}

type ConfirmUpload201JSONResponse Image

func (response ConfirmUpload201JSONResponse) VisitConfirmUploadResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type ConfirmUpload400ApplicationProblemPlusJSONResponse Problem

func (response ConfirmUpload400ApplicationProblemPlusJSONResponse) VisitConfirmUploadResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ConfirmUpload404ApplicationProblemPlusJSONResponse Problem

func (response ConfirmUpload404ApplicationProblemPlusJSONResponse) VisitConfirmUploadResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ConfirmUpload409ApplicationProblemPlusJSONResponse Problem

func (response ConfirmUpload409ApplicationProblemPlusJSONResponse) VisitConfirmUploadResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type ConfirmUpload500ApplicationProblemPlusJSONResponse Problem

func (response ConfirmUpload500ApplicationProblemPlusJSONResponse) VisitConfirmUploadResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreatePresignRequestObject struct {
	Body *CreatePresignJSONRequestBody
}

type CreatePresignResponseObject interface {
	VisitCreatePresignResponse(w http.ResponseWriter) error
}

type CreatePresign200JSONResponse PresignResponse

func (response CreatePresign200JSONResponse) VisitCreatePresignResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreatePresign400ApplicationProblemPlusJSONResponse Problem

func (response CreatePresign400ApplicationProblemPlusJSONResponse) VisitCreatePresignResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreatePresign500ApplicationProblemPlusJSONResponse Problem

func (response CreatePresign500ApplicationProblemPlusJSONResponse) VisitCreatePresignResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PromoteImagesRequestObject struct {
	Body *PromoteImagesJSONRequestBody
}

type PromoteImagesResponseObject interface {
	VisitPromoteImagesResponse(w http.ResponseWriter) error
}

type PromoteImages200JSONResponse struct {
	Promoted *[]Image `json:"promoted,omitempty"`
}

func (response PromoteImages200JSONResponse) VisitPromoteImagesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PromoteImages400ApplicationProblemPlusJSONResponse Problem

func (response PromoteImages400ApplicationProblemPlusJSONResponse) VisitPromoteImagesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PromoteImages404ApplicationProblemPlusJSONResponse Problem

func (response PromoteImages404ApplicationProblemPlusJSONResponse) VisitPromoteImagesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PromoteImages409ApplicationProblemPlusJSONResponse Problem

func (response PromoteImages409ApplicationProblemPlusJSONResponse) VisitPromoteImagesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type PromoteImages500ApplicationProblemPlusJSONResponse Problem

func (response PromoteImages500ApplicationProblemPlusJSONResponse) VisitPromoteImagesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteImageRequestObject struct {
	Id     string `json:"id"`
	Params DeleteImageParams
}

type DeleteImageResponseObject interface {
	VisitDeleteImageResponse(w http.ResponseWriter) error
}

type DeleteImage204Response struct {
}

func (response DeleteImage204Response) VisitDeleteImageResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteImage404ApplicationProblemPlusJSONResponse Problem

func (response DeleteImage404ApplicationProblemPlusJSONResponse) VisitDeleteImageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteImage500ApplicationProblemPlusJSONResponse Problem

func (response DeleteImage500ApplicationProblemPlusJSONResponse) VisitDeleteImageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetImageRequestObject struct {
	Id string `json:"id"`
}

type GetImageResponseObject interface {
	VisitGetImageResponse(w http.ResponseWriter) error
}

type GetImage200JSONResponse Image

func (response GetImage200JSONResponse) VisitGetImageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetImage404ApplicationProblemPlusJSONResponse Problem

func (response GetImage404ApplicationProblemPlusJSONResponse) VisitGetImageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetImage500ApplicationProblemPlusJSONResponse Problem

func (response GetImage500ApplicationProblemPlusJSONResponse) VisitGetImageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateImageRequestObject struct {
	Id   string `json:"id"`
	Body *UpdateImageJSONRequestBody
}

type UpdateImageResponseObject interface {
	VisitUpdateImageResponse(w http.ResponseWriter) error
}

type UpdateImage200JSONResponse Image

func (response UpdateImage200JSONResponse) VisitUpdateImageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateImage404ApplicationProblemPlusJSONResponse Problem

func (response UpdateImage404ApplicationProblemPlusJSONResponse) VisitUpdateImageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateImage500ApplicationProblemPlusJSONResponse Problem

func (response UpdateImage500ApplicationProblemPlusJSONResponse) VisitUpdateImageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetDeliveryUrlRequestObject struct {
	Id     string `json:"id"`
	Params GetDeliveryUrlParams
}

type GetDeliveryUrlResponseObject interface {
	VisitGetDeliveryUrlResponse(w http.ResponseWriter) error
}

type GetDeliveryUrl200JSONResponse struct {
	ExpiresAt time.Time `json:"expiresAt"`
	Url       string    `json:"url"`
}

func (response GetDeliveryUrl200JSONResponse) VisitGetDeliveryUrlResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetDeliveryUrl404ApplicationProblemPlusJSONResponse Problem

func (response GetDeliveryUrl404ApplicationProblemPlusJSONResponse) VisitGetDeliveryUrlResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetDeliveryUrl500ApplicationProblemPlusJSONResponse Problem

func (response GetDeliveryUrl500ApplicationProblemPlusJSONResponse) VisitGetDeliveryUrlResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ProcessImageRequestObject struct {
	Body *ProcessImageJSONRequestBody
}

type ProcessImageResponseObject interface {
	VisitProcessImageResponse(w http.ResponseWriter) error
}

type ProcessImage202Response struct {
}

func (response ProcessImage202Response) VisitProcessImageResponse(w http.ResponseWriter) error {
	w.WriteHeader(202)
	return nil
}

type ProcessImage500ApplicationProblemPlusJSONResponse Problem

func (response ProcessImage500ApplicationProblemPlusJSONResponse) VisitProcessImageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List/search images by owner/filters
	// (GET /images)
	ListImages(ctx context.Context, request ListImagesRequestObject) (ListImagesResponseObject, error)
	// Confirm upload (HEAD against S3), persist metadata
	// (POST /images/confirm)
	ConfirmUpload(ctx context.Context, request ConfirmUploadRequestObject) (ConfirmUploadResponseObject, error)
	// Create a presigned PUT URL for uploading an image to MinIO/S3
	// (POST /images/presign)
	CreatePresign(ctx context.Context, request CreatePresignRequestObject) (CreatePresignResponseObject, error)
	// Promote images from a product draft to a final product
	// (POST /images/promote)
	PromoteImages(ctx context.Context, request PromoteImagesRequestObject) (PromoteImagesResponseObject, error)
	// Delete image (soft or hard, per policy)
	// (DELETE /images/{id})
	DeleteImage(ctx context.Context, request DeleteImageRequestObject) (DeleteImageResponseObject, error)
	// Get image metadata
	// (GET /images/{id})
	GetImage(ctx context.Context, request GetImageRequestObject) (GetImageResponseObject, error)
	// Update image metadata (alt, role, order)
	// (PATCH /images/{id})
	UpdateImage(ctx context.Context, request UpdateImageRequestObject) (UpdateImageResponseObject, error)
	// Generate a signed imgproxy URL for delivery with requested params
	// (GET /images/{id}/url)
	GetDeliveryUrl(ctx context.Context, request GetDeliveryUrlRequestObject) (GetDeliveryUrlResponseObject, error)
	// Trigger (or retry) variant generation for an image
	// (POST /internal/images/process)
	ProcessImage(ctx context.Context, request ProcessImageRequestObject) (ProcessImageResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// ListImages operation middleware
func (sh *strictHandler) ListImages(ctx *gin.Context, params ListImagesParams) {
	var request ListImagesRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListImages(ctx, request.(ListImagesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListImages")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(ListImagesResponseObject); ok {
		if err := validResponse.VisitListImagesResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// ConfirmUpload operation middleware
func (sh *strictHandler) ConfirmUpload(ctx *gin.Context) {
	var request ConfirmUploadRequestObject

	var body ConfirmUploadJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ConfirmUpload(ctx, request.(ConfirmUploadRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ConfirmUpload")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(ConfirmUploadResponseObject); ok {
		if err := validResponse.VisitConfirmUploadResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreatePresign operation middleware
func (sh *strictHandler) CreatePresign(ctx *gin.Context) {
	var request CreatePresignRequestObject

	var body CreatePresignJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreatePresign(ctx, request.(CreatePresignRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreatePresign")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(CreatePresignResponseObject); ok {
		if err := validResponse.VisitCreatePresignResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PromoteImages operation middleware
func (sh *strictHandler) PromoteImages(ctx *gin.Context) {
	var request PromoteImagesRequestObject

	var body PromoteImagesJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PromoteImages(ctx, request.(PromoteImagesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PromoteImages")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PromoteImagesResponseObject); ok {
		if err := validResponse.VisitPromoteImagesResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteImage operation middleware
func (sh *strictHandler) DeleteImage(ctx *gin.Context, id string, params DeleteImageParams) {
	var request DeleteImageRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteImage(ctx, request.(DeleteImageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteImage")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(DeleteImageResponseObject); ok {
		if err := validResponse.VisitDeleteImageResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetImage operation middleware
func (sh *strictHandler) GetImage(ctx *gin.Context, id string) {
	var request GetImageRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetImage(ctx, request.(GetImageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetImage")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetImageResponseObject); ok {
		if err := validResponse.VisitGetImageResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateImage operation middleware
func (sh *strictHandler) UpdateImage(ctx *gin.Context, id string) {
	var request UpdateImageRequestObject

	request.Id = id

	var body UpdateImageJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateImage(ctx, request.(UpdateImageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateImage")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(UpdateImageResponseObject); ok {
		if err := validResponse.VisitUpdateImageResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDeliveryUrl operation middleware
func (sh *strictHandler) GetDeliveryUrl(ctx *gin.Context, id string, params GetDeliveryUrlParams) {
	var request GetDeliveryUrlRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetDeliveryUrl(ctx, request.(GetDeliveryUrlRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDeliveryUrl")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetDeliveryUrlResponseObject); ok {
		if err := validResponse.VisitGetDeliveryUrlResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// ProcessImage operation middleware
func (sh *strictHandler) ProcessImage(ctx *gin.Context) {
	var request ProcessImageRequestObject

	var body ProcessImageJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ProcessImage(ctx, request.(ProcessImageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ProcessImage")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(ProcessImageResponseObject); ok {
		if err := validResponse.VisitProcessImageResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xa627bOBZ+FUK7PxKs60tubQ3Mj9zaKtM2mVw67XSDDi0eSWwkUiWpJG5gYB9in3Cf",
	"ZMGLZMmSE9vddgJs/wSOJJKH5/Kd7xzyzgt4mnEGTElveOfJIIYUm5/7nIVUpKfwJQep9JNM8AyEomDe",
	"48Q8VOMMvKEnlaAs8iYdL4ghuJJ5ql8SkIGgmaKceUMPulG3g85e7W5s76AYblHIBcKEUP0eJ4gyBZGg",
	"aozMHF7HY3mS4FEC3lCJHDrNxQTXL++8vwsIvaH3t950Oz23l56f4ghO9YeTjpdnCcfknF8Bawp4RiMG",
	"BB39fo6U/gKFgqcoEyBpxJAAmXEmwet4KWWvgUUq9oaDhlRaLPiSUwHEG36srdgxWnNiX5Yj+egzBEqL",
	"Z2RdQtcCsAKya96GXKRYeUOPYAVPFE21pI0hMZax/vpB1VKiP4NbnGb6K4+m0af+4M3u3v7B4Ytut9s2",
	"+RWMW7S6ia5gjHiIVAyICxpRY22z1ZZJUi15225TTmhIl9suv2EgfNI6n3l3bp7e70HH5YeruJykX6v7",
	"MV4OwrxRWOVyocnO7Kfag0XS1PFx5mLoP//6NyJUQKDQxelrREOU5aOEBogLdE0xygS/HS8SWddYUOxQ",
	"gSpIHxTznR2gx7rJsBB43IgHSryq6qcmcqq1XlRESmrtanRYKqzq+DW3mBtSJ1gF8eJxxQUB0dTyCZcG",
	"qxBlxpczwUkeKBThJAExnvpfxcZLustk3g5O3TzANLR+9FJMNZ5Ml+YqBlHRwHQ3VQeqzJABI/qLAhRB",
	"myATPAAp7XMBmOipQ0wT85ZAAgpI6yrH1Wgq17AaOhA4VHZ2/a9eUs4R9sSi7dy0E3CmgKnZhQya9D5n",
	"oOW2/2Rs+vsGRln5D76moV67im2V0Q2RQpoAwxaUpmNkzKH7OYseSgc1DKr7k1EL8g90cJqPkH+w4HQ/",
	"DrZmU+RX0O4/GivQgZjiW5pqEwz6W8+2n+70jfjuUTMeZrCgHQZKfXdq1i5RYG72LH3HJeqG88BtRgVI",
	"vyX3n5+/1vuSEHBGZHsoO8lfASYgLICU7OWktlDDaA1ZlyMiWg+YMsoiZAeiFBQmWGG0dgXjDio16X76",
	"pIO0njoIVNBdb3NrO9GFTSdlNs0F9RajNHpkZ4beTBXcVFe7xfgogRauePpi/+mz/lPkPkAHoDBNpMWQ",
	"iqKJed6qchCCi3r+qo8NKSTtzCAFKR0Ra2qisYl6uut4lEmFWQAP67VKAZr+pqhK2pmQEjiAOaxGOWRY",
	"yqLKBphdsZRqjsVSrmAuPhONaVa0B3DMgK5smt4PEU+pUkAMm8nsgggnjjPKgkoSl1VK886LutIyKb+G",
	"1gU1CTKrBTwbI8WL1C57d+6XTya9breLMCNIgJ4I8YQgq5gKXow4TwAzvVo58kFlzFij0GF1Cid8m0kK",
	"5tWwRQw0ilW7cy1A1R0FXIqjN/OkivN01Or6c3nxDSUqbnvVjL6JibeQN/eye+KbAjPFDEcaOJ2/lXFl",
	"eRE6A3FNA0C7J77X8a5BSDt+0O13NzZNws2A4Yx6Q2+z2+9uarNgFRsN96ZOHIHRtNY/1iJos3uvqVR+",
	"sW6GBU5BmdTx8c6jepUvuWVvVm+1hGiz8hJJftK5Z1LjQtMpGw7YPrQk3IsJUytV5s2Z2bpvOiOBEOea",
	"iQ8eIg/zJzxzBUJz0u1+haVs9B8iKJc6FC1/MGbd6PcrtNPk/CxLaGBs3PssOZv2TZoRWELTQiWUrf5b",
	"cCurJ6NKqJR7b88gXOFk8UCaqSl/1VNs37v/zKbnfzT1cN8+i6zfsqjPFAhdyOqwBIEOdRI38so8TbEY",
	"u6DqScAiiIuMMBpb2tMLaWICTI9wwdkLbCfLWIfLlih1ra4LQ2UccwGp9jgZL2B7B3XGuvxK/73GSQ5l",
	"fentJTi4QpIBvtKiFVy8KOFqTNCD8VE8ehnQY3rkX3z1B2+pL312uh3s+zv+Vfb+3f7R8263a3W3mLpn",
	"OnmTerrRqW/ScPrBUk6/gFO3mNrAL+FBngJTyJX02ue2fqzP7WGCSuXo1bd+5OoXrvh2VAIxrlDIc+Y0",
	"8fxHyqI9JaGBQmu2V2sCCN1QFRtCIHEKhiDgxLQGkIssIOuPFCqc6xdF09qrw90DhCOsKTo621zvoEwn",
	"fKnKeqqGHK71ew9yGKd1dec3IYfhfIcFa6pgSK3hUe9UTBsT1W5E2W7wSKg+9QdHu3v7B4ONwxebL7e2",
	"X+0c/fr0zdtnJ7/VunDD2U5NHaIsVRs829za3lkCeGZ6OQsBT//bELdS4T/Xub6lZt+3kz9panSyEhjD",
	"+GgQvLy9/vD7b/SYSYo33m37nzkNbJO8UmZ7sVKZHPZ6moHwbrf7/slu+vXJoZX5l+f9/j/zfn9jxz4+",
	"oxHDKhfwy5J4P9sGaYkd9wkQ0yV+NND7GBHE6Abh4hgICDq5ODdq09WFta4uLzBzcKk4ekOZf9w725wB",
	"E1PIzgcTV1qX9cLqYIKTpBYVoeCpjeyHQcHWyO5UgJ+4jq0GCPKpP/j1/Yc/7NDNLaepkbSVz0qrFfXT",
	"x7bzJffo/Yc/9P+XS8q2RLzUWhr/M5iaVxQ4RyDfWhcsQuLt3ihnSM9ru/f/bwzLEs23XKEXfzWvIrmu",
	"t11PS797nKDnIqKorswxOC6PuwxV0TCHUWiOcotjnSra3VEysXW4drom2B2Y5747BG5rjWRYxdMinxJv",
	"NipX6GfEWJD2NkGIEwmdezqDdiNFww9RZlG+2hA82EMCAi6IZpUp1iZJxi2twZYmw1bL6RBUwvWvDphH",
	"6KRWPy7prkkeKsQF0hY2rB5lPKHB2FQmrb25l6C+m/t9axdppYLaNmx++kqLr7wE5RxlWueZNq69FVB3",
	"jIuM4O8ITZfLMrsl3MLec/gODGYlh7SK/Ilg87zS6mfGMdEaTlRxeGsuoqw3EmvPXQKah2sHkNBrEGN7",
	"RPujkuv0vKiaX6tKeYtTQDy01dSTCJiWG0hx0oTWaIjglkol19uOLNuXvaktuMoBQvzNM4S0vu3iWkrA",
	"r0G4ewy2lRLSRNuEMkmJufaQK/PrcuH9uoPdVhbjFdfrvE4pQ+WRuwZjLsB0PNdFyli0xOpfcpxQNW5f",
	"/tl27UZIf7XzHJKJ+edDxeyblbn73e1ydpano/smVyo5K+94zPNTP0Q0jcxdOUSlbXNGuQBie6Gy6Mwg",
	"024yoddBmKE/XfvpT2RiDt3QJEEjQJQFSW4vWE2F/u6HT06YZa5L5qvcBjEgM13scuGzpZ9JoZWqWFRE",
	"GLl+U+mKRdOJOHi33ujIBBDrdMXZl1uq0n0KQMp7u0/6g4L2rEpRZs4/9WxzLqpkAlznqD1J2BuW+hu0",
	"ViQICWq9g2iIcmmi6cHbOYswoY2WywNBAJlWqVZ35U7k43SZc0GjCARa4wIJUGK8XmZUl2MpZ/a2vWtS",
	"6pUm/w0AAP//z/igG/0vAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
